id: I02530110
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T19:25:57.786919'
last_modified: '2022-06-18T19:25:57.786930'
parser: null
source_metadata:
  title: Record of teachings received of the rGyud sde kun btus
  author: འཇམ་དབྱངས་བློ་གཏེར་དབང་པོ།
  description: 'Digital version 2.0 {Tibetan}; master xml (completed: 2020-10-29);
    glosses not encoded, no thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།; This text was published by Sachen International,
    Kathmandu (Nepal). (src)
  - Text input:Guru Lama, Sachen International, Kathmandu (Nepal) (si)
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/779
  bases:
    76fc:
      title: Record of teachings received of the rGyud sde kun btus
      order: 1
      base_file: 76fc.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
